### ISSUE TITLE
User friendly navigation and responsive design

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#1]
**User Story:**

As a tourist considering visiting the area I want to see images and descriptive text for available accommodations and amenities both on the property and in the surrounding area.

**Acceptance Criteria:**

- [x] The homepage displays a gallery of hero images of the property and local amenities that respond to different screen sizes.
- [x] Each accommodation is detailed briefly with text and images on cards and links to more detailed information easily.
- [x] The images and text detailing the property are responsive and look good on all main device sizes.
- [x] A footer has contact information.

**Tasks:**

- [x] Add responsive HTML on the homepage utilizing Bootstrap.
- [x] Style the nav bar, header gallery, two categories of accommodation, local amenities, testimonials and footer using a professional looking colour palette and fonts.
- [x] Add a booking page using Bootstrap with nav bar, footer, property selector and date selectors for the beginning and ending of the rental range. Add inputs for visitor details as well as a submit button that triggers a success page and posts the data to the site's owners with details of the booking request.
- [x] Add a success page with a thank you message and a button linking back to the home page.
