### ISSUE TITLE
Add correct text and alt detail

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#10]
**User Story:** 

As visitor I want to see inviting descriptions on the cards to convince me a visit is worthwhile. Because I am blind I want the image descriptions available for readers.

**Acceptance Criteria:**

- [x] The cards all have descriptions.
- [x] The images all have alt description text.

**Tasks:**

- [x] Add text to cards.
- [x] Add text to alt value of images.
