### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#2]
**User Story**

As a prospective visitor, I want to read testimonials from previous visitors so that I can feel confident about visiting.

**Acceptance Criteria:**

- [x] The homepage has a section with testimonials.
- [x] Each testimonial includes the vistor's name, dates visited, and comments with link to google review and profile pic.
- [x] The testimonials section is responsive and looks good on all main device sizes.

**Tasks:**

- [x] Create an HTML section for testimonials on the homepage.
- [x] Style the testimonials section using Bootstrap.
- [x] Populate the section with 3 sample testimonials including names, events, and comments.
- [x] Link to google reviews.
