### ISSUE TITLE
Success Page

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#3]
**User Story:** 

As booked visitor I want to see confirmation that my reservation has been processed successfully.

**Acceptance Criteria:**

- [x] The booking form submission triggers a link to success page.
- [x] The success page has a Thank You! message and button linking back to the homepage.

**Tasks:**

- [x] Build an HTML success page using Bootstrap.
- [x] Add the button linking to the home page.
- [x] Apply Bootstrap classes to create a visually appealing layout across all screen sizes.
