### ISSUE TITLE
Detailed accommodation information (accommodation section of home page & new page)

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#4]
**User Story:** 

As a potential holiday visitor, I want easy access to detailed information about each property so that I can decide if I want to visit.

**Acceptance Criteria:**

- [x] Below the header hero image is an accommodation section with clickable cards for cottages & rooms to differentiate the two types of accommodations.
- [x] Each clickable accommodation-type card on the home page takes visitors to a corresponding section on a separate page.
- [x]  These sections have clickable cards displaying a hero image and brief description for each cottage and room respectively.
- [x] Clicking on cards links to a gallery in a third section of the new page containing larger images in an interactive carousel, more descriptive text and pricing information for the selected accommodation.
- [x] Each accommodation gallery has two buttons. One button links to the booking page. The other returns the user to the home page.

**Tasks:**

- [x] Add clickable cards for cottages & rooms to an accommodation section of home page in a responsive bootstrap container.
- [x] The clickable cards must include a hero image and brief description.
- [x] Create the accommodation page with three responsive sections. Sections for clickable cards 
 for cottages & rooms sections and a section below for larger galleries of the individual accommodations.
- [x] Create clickable cards, similar to the cottage and room cards on the home page, for each accommodation and organize them in the cottages & rooms sections of the accommodation page in a responsive Bootstrap container.
- [x]  Create linked image galleries and descriptive text for each accommodation further down the accommodation page in a responsive bootstrap container.
- [x] Add buttons below the accommodation galleries that link to either the booking form or home page.
