### ISSUE TITLE
Gallery Page for each rental accommodation

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#5]
**User Story:** 

As a potential visitor, I want detailed information for each rental accommodation easily accessible via two categories (cottages & rooms) from the home page.

**Acceptance Criteria:**

- [ ] The rental accommodation categories (cottages and rooms) display cards for each property that link to gallery pages below the card listings.
- [ ] Each accommodation's page header is a gallery carousel displaying images of the accommodation with a paragraph of details below and two buttons below that, one linking back to the home page and one to the booking form.

**Tasks:**

- [ ] create two sections with Add a responsive carousel to the header in bootstrap and HTML.
- [ ] Add a responsive paragraph detailing the property and pricing using Bootstrap and HTML.
- [ ] Add two buttons below the carousel and text, one linking back to the home page and the other to a booking form using Bootstrap and HTML.
- [ ] Visitors can scroll down the Cottages .
- [ ] The book now button carries the sselected date range and rental space details into the booking form.
