### ISSUE TITLE
Booking Form Page

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#6]
**User Story:** 

As a visitor I want a form to request a booking for my visit.

**Acceptance Criteria:**

- [x] Visitors can navigate to the booking form from a button below the carousel in the header or on the individual accommodation galleries.
- [x] The booking form allows visitors to enter their contact details, a message, select the specific property they are interested in and the date range for the booking.
- [x] The submit button produces a success page and sends an email to the site's owners with details of the request.

**Tasks:**

- [x] Add a book now button to the header linking to the booking form.
- [x] Add book now buttons to each accommodation's page linking to the booking form.
- [x] Create a responsive booking form using Bootstrap that allows visitors to select the accommodation, enter contact details, a message, date range for their visit as well as a submit button.
- [x] Style the booking form using Bootstrap for responsiveness using the same colour palette and fonts seen on the home page.
- [x] Ensure that submitting the form triggers a success page for the visitor.
