### ISSUE TITLE
Project Planning

### ISSUE THREAD

**Issue by Jordalenko** [Jordalenko/Wern-Fawr-B-B#7]
Build Preliminary Project Plan.

**Acceptance Criteria:**

- [x] Wireframes of layout created for all pages.
- [x] Wireframes for all pages created for bootstrap responsive sizing.
- [x] Begin readme
- [x] Mentor feedback

**Tasks:**

- [x] All wireframes in pdf.
- [x] All Bootstrap sizes for wireframes in pdf
- [x] create readme.md
- [x] Add Mentor notes changes to wireframes.
